# This is a basic workflow to help you get started with Actions

name: Autobuild

# Controls when the action will run. Triggers the workflow on push
# events but only for the dev branch
on:
  push:
    branches: [ workflowtest ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Hello, world!\nRunning setup script..."
        shell: bash

      # Runs a set of commands using the runners shell
      - name: Run a script
        run: yes n | ./setup.sh
        shell: bash

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Setup completed."
        shell: bash
