# This is a basic workflow to help you get started with Actions

name: Autobuild

# Controls when the action will run. Triggers the workflow on push
# events but only for the dev branch
on:
  push:
    branches: [ workflowtest ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Conan
        run: pip install conan
        shell: bash

      # Runs a set of commands using the runners shell
      - name: Run setup.sh
        run: yes n | ./setup.sh || if [[ $? -eq 141 ]]; then true; else exit $?; fi
        shell: bash
        
      - name: Run Conan install
        run: conan install ./FallingSandSurvival/conanfile.txt -g visual_studio --install-folder ./x64/Release/.conan -s arch=x86_64 -s build_type=Release -s compiler.toolset=v141 -s compiler.version=16 -s compiler.runtime=MDd  --build=missing --update
        shell: bash
        
      - name: Build Binary
        run: bash -c "'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\Bin\\msbuild.exe' -p:Configuration=Release;Platform=x64"
        shell: bash
